# Generated by Django 3.2.16 on 2024-01-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20240104_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(blank=True, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='projects.cities'),
        ),
    ]
