# Generated by Django 3.2.16 on 2024-01-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_signcommercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcommercial',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercials_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
