# Generated by Django 3.2.16 on 2024-01-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_jobcommercial_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
