# Generated by Django 3.2.16 on 2024-01-08 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_delete_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobCommercial',
            new_name='Job',
        ),
    ]
