# Generated by Django 3.2.16 on 2024-01-08 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_rename_jobcommercial_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignCommercial',
            new_name='SignJob',
        ),
    ]
