# Generated by Django 3.2.16 on 2024-01-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_signcommercial_signjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signjob',
            old_name='commercial',
            new_name='job',
        ),
    ]
