# Generated by Django 3.2.16 on 2024-01-18 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_rename_employer_company_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignJob',
            new_name='ApplyJob',
        ),
    ]
