# Generated by Django 3.2.16 on 2024-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_signjob_applyjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='manager',
            new_name='employer',
        ),
    ]
