# Generated by Django 3.2.16 on 2024-01-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20240118_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='manager',
        ),
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
