# Generated by Django 3.2.16 on 2024-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20240118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
